<?php
// This file generated by Propel 1.6.8 convert-conf target
// from XML runtime conf file D:\Programmes\PoGo\WEB\application\propel\runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'pogo' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:host=127.0.0.1:3306;dbname=pogo',
        'user' => 'pogo',
        'password' => 'pogo',
        'settings' => 
        array (
          'charset' => 
          array (
            'value' => 'utf8',
          ),
        ),
        'options' => 
        array (
          'MYSQL_ATTR_INIT_COMMAND' => 
          array (
            'value' => 'SET NAMES utf8 COLLATE utf8_general_ci',
          ),
        ),
      ),
    ),
    'default' => 'pogo',
  ),
  'generator_version' => '1.6.8',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-pogo-conf.php');
return $conf;